### ISSUE TITLE
wild随机传送功能存在BUG

### ISSUE THREAD

**Issue by IamTuDou0** [wisdommen/UltiTools#126]
在服务器中只有OP可以使用wild命令，即便使用权限管理插件给普通用户分配命令权限也无法正常使用该功能
使用的插件版本：
UltiCoreAPI              1.2.5
UltiEconomy             2.7.3
UltiTools                   5.2.0
LuckPerms-Bukkit     5.3.86

**Comment by qianmo2233** [comment]
问题已经修复，下个版本更新

#127
