### ISSUE TITLE
spawn出生点半径150内玩家无法破坏，如何取消他

### ISSUE THREAD

**Issue by MisakaMikoyo** [wisdommen/UltiTools#138]
您好 。spawn出生点半径150内玩家无法破坏，如何取消他，或更改范围。

**Comment by wisdommen** [comment]
这个可能是spigot自带的出生点保护？

**Comment by MisakaMikoyo** [comment]
不知道哦  您知道怎么改吗  我使用ess插件没有这个问题     还有这边权限表在哪里获取呢

**Comment by qianmo2233** [comment]
ess插件可能覆盖掉了spigot的出生点保护
服务端目录的server.properties文件，打开后找到spawn-protection这个选项 后面改成0即可取消
权限可以在下面这两个地方找，目前还在整理当中
[【金山文档】 UltiTools指令&权限一览](https://kdocs.cn/l/cdaz72eBk06b)
[UltiTools 使用文档](https://doc.ultitools.ultikits.com/)

**Comment by MisakaMikoyo** [comment]
好的感谢回复
