### ISSUE TITLE
死亡惩罚问题

### ISSUE THREAD

**Issue by 2022557306** [wisdommen/UltiTools#26]
在玩家死亡时如果钱不够或者没有钱，会一直扣钱
而开启物品掉落的话，打开死亡掉落，死亡之后回来捡东西后东西会一直消失，

**Comment by wisdommen** [comment]
感谢反馈，暂时建议先关闭死亡掉落或者说死亡惩罚更合适点

**Comment by wisdommen** [comment]
已修复，等待下次更新
