### ISSUE TITLE
UltiTools v2.4.1 bug反馈

### ISSUE THREAD

**Issue by ZeroBloodedge** [wisdommen/UltiTools#3]
使用环境：
- Spigot 1.16.1服务端
- 经济前置Vault、XConomy2.6.8
- PlaceholderAPI 2.10.9
- 传送门插件SimplePortals

问题说明：
1. 远程背包购买的时候“显示未安装经济前置”
2. 用/mw创建多世界以后，重启服务器会检测不到多世界

问题复现：
- 远程背包问题
1. 前置安装Vault 1.7.3，经济插件为XConomy 2.6.8
2. 使用Quickshop正常，可以正常购买卖出东西
3. 经济插件相关功能，如给予、收回金钱、转账、/balancetop等均正常使用
4. 使用/bag打开远程背包页面，选择购买背包，显示“未安装经济前置”

- 多世界问题
1. 更新UltiTools 2.4.1后，之前通过UltiTools 2.2.5创建的多世界无法读取，输入/mw list不显示除主世界、下界、末地以外的世界
2. 使用/mw create创建同名世界会提示“该世界已存在”
3. 使用/mw 世界名 进行传送无法进行，显示“/mw help”
4. 之前使用SimplePortals设置的传送门锚点无法读取，提示世界不存在
5. 删除服务器下的多世界对应的文件夹，还有UltiTools目录下关于多世界的yml配置文件，重启服务器，使用/mw create创建世界，一切正常，能够传送，传送门能够设置锚点
6. 关闭服务器并重启，仍然出现(1)中的问题，/mw list不显示刚刚创建的新世界，无法传送，传送门锚点丢失

**Comment by wisdommen** [comment]
8.19更新，版本2.4.3
1.修复了创建的多世界无法加载的bug

已经修复了多世界的问题，请上mcbbs下载最新版本吧！
远程背包的问题即将着手修复

**Comment by wisdommen** [comment]
8.19更新，版本2.4.4
1.真正脱离了UltiEconomy的依赖
2.修复了添加远程背包时无法找到经济前置的问题

好了，已经将这两个bug修复，请前往mcbbs下载最新版本。感谢你的反馈
