### ISSUE TITLE
权限问题

### ISSUE THREAD

**Issue by skyatgit** [wisdommen/UltiTools#40]
https://github.com/wisdommen/UltiTools/blob/master/src/main/java/com/ultikits/ultitools/commands/WarpCommands.java
warp，warps命令的判断是否为ultitools.warp.admin漏加了

**Comment by wisdommen** [comment]
没有漏加ultitools.warp.admin，是判断符的问题

**Comment by wisdommen** [comment]
不对，应该是权限组的问题，结案
