### ISSUE TITLE
权限组问题

### ISSUE THREAD

**Issue by skyatgit** [wisdommen/UltiTools#41]
权限组赋权后没作用，会导致配置文件中permissions:值的中括号消失(即使存在也不起作用)反正warps命令没有检测到某个权限组的人的权限，不能正常移除权限组的权限（表现在配置文件中）

**Comment by skyatgit** [comment]
不知道player.hasPermission方法能不能检测到玩家所在组的权限（理论上是应该可以的）
那应该就是给权限组赋权时的问题

**Comment by wisdommen** [comment]
yaml语法就是这样的，中括号是空数组
