### ISSUE TITLE
关于邮件系统的建议

### ISSUE THREAD

**Issue by AnsonSkywalker** [wisdommen/UltiTools#43]
这里是一位基友开黑小服腐竹，PaperSpigot 1.12.2。相同内容的反馈在MCBBS也发了一份。

UltiTools的邮件系统指令为/email，经本人实测会和AuthMeReloaded插件的邮件验证功能指令/email冲突，结果就是AuthMe的邮件功能优先生效把UltiTools的邮件给覆盖掉了。

即便是我手动将全服玩家的使用AuthMe邮件功能的权限禁了也无济于事。至于AuthMeReloaded我是死活找不到有什么关闭它鸡肋无比的邮件系统的方法。

目前的解决方案是使用/ultitools:email来替代原本的/email。但指令一长不仅不方便于记忆，玩家用后也表示输起来又臭又长。

是否考虑过在下一个版本更换邮件指令为别的不易冲突的指令，或是支持在配置文件中自定义各功能模块的指令头呢？毕竟我们的定位可是“基础插件”。

**Comment by AnsonSkywalker** [comment]
如果可以，我更希望是能自定义各功能模块的指令头，还有就是希望能针对所有功能模块都允许通过配置文件自行配置。

例如：

家插件可以配置具体的title和subtitle样式；
TPA功能我希望能像家插件一般自定义传送前摇时间，我的服倾向原版纯净生存玩法，鼓励玩家使用地狱交通系统，传送系统使用过于便捷会破坏原版纯净玩法体验。
等等等等……

**Comment by wisdommen** [comment]
首先很开心能收到你的反馈。

因为定位是基础插件，所以所有的命令当然是怎么简单怎么来，我可以加一些其他的变体命令，但是不会去改变email这个指令，我可以加上alias，比如ema或者ultimail

还有一个是，我目前没有那么多精力做特别深的可自定义化内容，毕竟内容实在有些多。我只能想到点做点，得慢慢来。还有就是很多用户给我的反馈都是各种各样的，甚至是冲突的，其中的取舍我也是很是为难。就比如很多人希望我简化配置文件，但是简化配置文件就必然导致可自定义内容减少。

**Comment by AnsonSkywalker** [comment]
感谢您在百忙之中抽空回复我的反馈。期待下个版本的UltiTools您能为我们广大腐竹带来更多的惊喜！

**Comment by wisdommen** [comment]
没事，不过别关，我以后好跟进
