### ISSUE TITLE
跟R键整理mod冲突。

### ISSUE THREAD

**Issue by fuwenjiang-cd** [wisdommen/UltiTools#49]
安装版本：
UltiCoreAPI-1.1.7.jar
UltiEconomy-2.6.9.jar
UltiLevel-2.1.2.jar
UltiTools-5.0.4.jar
 R键整理：https://www.curseforge.com/minecraft/mc-mods/inventory-profiles

希望UltiTool可以出一个R键整理的功能。

**Comment by wisdommen** [comment]
R键整理的话那是mod吧，冲突的话我是实在没办法

**Comment by fwj1991** [comment]
建议：UltiTool可以出一个R键整理的功能。
