### ISSUE TITLE
/home功能bug汇报 版本v2.6.5

### ISSUE THREAD

**Issue by ZeroBloodedge** [wisdommen/UltiTools#6]
使用环境：

- Spigot 1.16.1服务端
- UltiTools v2.6.5

问题说明：

- 在使用/sethome设置了一个家的情况下，使用/delhome 默认无法删除家，并且在另一个地方再使用/sethome无法覆盖之前默认的家

问题复现：

1. 首先在一个地方/sethome设置家

2. 使用/sethome尝试在另一个地方设置另一个默认家覆盖之前那个，显示如下

“**你已经有叫这个名字的家了！**”

3. 尝试使用/delhome 默认，来删除默认的家，显示如下

“**[家插件]你没有这个家！**”

希望能够达到的效果：

1. 可以使用/sethome直接覆盖之前的默认的家设置，不需要/delhome也可以

2. 如果无法做到，至少希望/delhome能够试别默认的家，不然删不掉也无法设置新的默认的家

非常感谢！

**Comment by wisdommen** [comment]
已修复，感谢反馈
