### ISSUE TITLE
关于 图形化密码登录 功能的bug

### ISSUE THREAD

**Issue by OcrSu** [wisdommen/UltiTools#76]
（玻璃板）图形化密码登录这个功能很棒
玩家进入服务器后确实可以弹出登陆界面
但是，一旦玩家在弹出窗口后，确认密码前 死亡；那么玩家复活后将没有办法登录（不会自动弹出界面了）
除非重新进入服务器

希望能改进

**Comment by wisdommen** [comment]
好的，我会改进这个问题

**Comment by OcrSu** [comment]
> 好的，我会改进这个问题

直接加个登陆保护？
