### ISSUE TITLE
关于Spawn功能（setspawn）的问题

### ISSUE THREAD

**Issue by OcrSu** [wisdommen/UltiTools#77]
插件的spawn是传送到玩家现在所在的世界的出生点
也就是说 你在下界使用spawn会跑到下界的spawn 在末地使用spawn会跑到末地的spawn
而末地和下界 包括数据包创建的维度 他的levelInfo 都是 DeviedWorldInfo 里面的写入相关的方法全是空的 
读取方法则是读取父WorldInfo -- 主世界的 ，所以导致怎么使用spawn都是回到主世界的坐标
并且还是当前维度的坐标 (大多数情况被被石头卡死 或者从天上掉下来)

希望能改进

**Comment by wisdommen** [comment]
抱歉一直没看到，这就改

**Comment by wisdommen** [comment]
已于5.1.9版本修复，感谢反馈
