### ISSUE TITLE
关于图形登录的建议

### ISSUE THREAD

**Issue by OcrSu** [wisdommen/UltiTools#78]
我发现R键整理之类的模组会破坏整个图形排列
可以添加一个检测和提示

检测：玩家是否登录，且登陆界面是否存在
否：弹出登陆界面
提示：若不小心按到背包整理键导致按键错乱，可以按esc关闭界面以重新打开

或者更好的方式

**Comment by wisdommen** [comment]
额，这个没办法的，因为R键整理是mod，插件没法检测本地端的操作。如果一直刷新的话会导致性能问题

**Comment by OcrSu** [comment]
好的
