### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by DevilJueChen** [wisdommen/UltiTools#8]
1.在放下箱子后聊天栏自动显示：
提示：可以输入/lock 锁上箱子，
可以输入/unlock 来解锁箱子。 
可以输入/[未来箱子共享指令] ID来共享箱子

2.希望添加功能：箱子共享
[未共享则显示]每次关闭箱子聊天栏自动显示：
提示：此箱子已上锁！
箱子主人：Player
可打开的人：Other player

**Comment by wisdommen** [comment]
感谢提出建议，已采纳放下箱子后的提示，箱子共享暂未采纳。
