### ISSUE TITLE
关于箱子锁的一些小建议

### ISSUE THREAD

**Issue by yzazzx2021** [wisdommen/UltiTools#94]
介于原版箱子容量过于窄小，
比起更多的箱子模组稍微逊色了点，
建议插件作者可以考虑一下兼容一下更多箱子模组，
这个是目前箱子种类最多的一款模组，也是知名度最高的模组，如果觉得模组会变，可以只兼容其中几个版本就行。

**Comment by wisdommen** [comment]
插件不会兼容模组的，这是公认的，特别是基础插件类，不可能专门去兼容某个模组的哦
