### ISSUE TITLE
gui登录的建议

### ISSUE THREAD

**Issue by h15588** [wisdommen/UltiTools#99]
建议增加指令登录功能，gui登录在mod较多时会导致玩家进入假创造模式（可以刷方块可以瞬间破坏方块，但是按右键恢复正常），只有自杀才能恢复正常，所有mod均单独测试没有问题，插件除了ulti全套与前置只有地形保护插件与死亡不掉落插件，客户端为arclight。关闭登录功能时安装其他登录插件会造成冲突无法登录。

**Comment by wisdommen** [comment]
mod服会有些问题，算是核心的问题吧，我是根据spigot原版核心开发的。arclight虽然是spigot的分支，但是会有方法上的更改，所以实在抱歉，无法对单独的mod核心做适配
